//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro
    {
        public int idCobro { get; set; }
        public System.DateTime fecha { get; set; }
        public double importe { get; set; }
        public int Credito_folioCredito { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
