//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CondicionCredito()
        {
            this.Credito = new HashSet<Credito>();
        }
    
        public int idCondicionCredito { get; set; }
        public string descripcion { get; set; }
        public bool estaActiva { get; set; }
        public int plazoMeses { get; set; }
        public bool tieneIVA { get; set; }
        public int tasaInteres { get; set; }
        public int Checklist_idChecklist { get; set; }
    
        public virtual Checklist Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credito> Credito { get; set; }
    }
}
