//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictamen
    {
        public int idDictamen { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fechaHora { get; set; }
        public bool estaAprobado { get; set; }
        public int Credito_folioCredito { get; set; }
        public int Usuario_idUsuario { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
