//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancieraBD : DbContext
    {
        public FinancieraBD()
            : base("name=FinancieraBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checklist> Checklist { get; set; }
        public virtual DbSet<ChecklistPolitica> ChecklistPolitica { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Cobro> Cobro { get; set; }
        public virtual DbSet<CondicionCredito> CondicionCredito { get; set; }
        public virtual DbSet<Credito> Credito { get; set; }
        public virtual DbSet<Dictamen> Dictamen { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<EstatusCredito> EstatusCredito { get; set; }
        public virtual DbSet<Politica> Politica { get; set; }
        public virtual DbSet<ReferenciaCliente> ReferenciaCliente { get; set; }
        public virtual DbSet<ReferenciaTrabajo> ReferenciaTrabajo { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
