//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ReferenciaCliente
    {
        [DataMember]
        public int idReferenciaCliente { get; set; }
        [DataMember]
        public string nombres { get; set; }
        [DataMember]
        public string apellidos { get; set; }
        [DataMember]
        public string descripcion { get; set; }
        [DataMember]
        public string telefono { get; set; }
        [DataMember]
        public int Cliente_idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
