//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaCliente
    {
        public int idReferenciaCliente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string descripcion { get; set; }
        public string telefono { get; set; }
        public int Cliente_idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
