//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosFinancieraIndependiente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Dictamen = new HashSet<Dictamen>();
        }
    
        public int idUsuario { get; set; }
        public string correoElectronico { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string contrasenha { get; set; }
        public int TipoUsuario_idTipoUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dictamen> Dictamen { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
